import Head from 'next/head'

import Footer from '../components/Footer'
import Header from '../components/Header'
import Nav from '../components/Nav'



export default function Home() {
  return (
    <div >
      <Head>
        <title>ARYAN Chandra</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav/>
      <Header />
      <Footer />




    </div>
  )
}
